SERVER_SOCKET_IP = '127.0.0.1'
SERVER_SOCKET_PORT = 9999
SERVER_ADDRESS = (SERVER_SOCKET_IP, SERVER_SOCKET_PORT)
IMAGE_ENCODE_DECODE_FORMAT = 'utf-8'
VIDEO_IMAGE_ENCODE_DECODE_FORMAT = '.jpg'
VIDEO_SOURCE = 1  # FaceTime camera | 0 - Raspberry Pi camera
SOCKET_TRANSMISSION_SIZE = 1024
