SERVER_HOST = '0.0.0.0'
SERVER_SOCKET_PORT = 9999
SERVER_FLASK_PORT = 5000
SERVER_SOCKET_ADDRESS = (SERVER_HOST, SERVER_SOCKET_PORT)

SERVER_MAX_QUEUE_SIZE = 5
IMAGE_ENCODE_DECODE_FORMAT = 'utf-8'
VIDEO_IMAGE_ENCODE_DECODE_FORMAT = '.jpg'

VIDEO_RECORDING_FRAME_RATE = 15.0  # In FPS
SOCKET_TRANSMISSION_SIZE = 1024  # In bytes
